### ISSUE TITLE
can authentication be disabled?

### ISSUE THREAD

**Issue by pillsilly** [svtslv/webdav-cli#1]
Hi 
can authentication be disabled?

**Comment by svtslv** [comment]
This is not secure. WebDAV provides full access to your disk. Everyone can delete all your data by running `curl -X DELETE ...`. Why do you need this?

**Comment by pillsilly** [comment]
well a app could only demand read/search from the webdav and wants to provide out of the box solution

your concern is ok but what about leave the option to user?
to prevent careless user we can enable the authentication by default(same to the other risky api like DELETE)




发自我的小米手机
在 Sviatoslav <notifications@github.com>，2020年3月17日 22:41写道：

This is not secure. WebDAV provides full access to your disk. Everyone can delete all your data by running curl -X DELETE .... Why do you need this?

**Comment by svtslv** [comment]
Now you can use the `--disableAuthentication` option, which also changes the default permission to `canRead` only.

**Comment by pillsilly** [comment]
well an user could demand only read/search featue from the webdav and also might want to use it with a minimal effort(e.g no auth required)

so why not to keep this options?
to prevent careless use we might enable the authentication by default(same to the other risky api like DELETE) 

thanks for the reply

**Comment by pillsilly** [comment]
that'd be awesome and thanks for the improvement.
